Refactor prometheus-provision script to add prometheus-liveness litmus job
Signed-off-by: harshita-sharma-mayadata <harshita.sharma@mayadata.io>

diff --git a/Openshift-EE/pipelines/Prometheus/stages/3-functional/ELHN-deploy-prometheus/prometheus-provision b/Openshift-EE/pipelines/Prometheus/stages/3-functional/ELHN-deploy-prometheus/prometheus-provision
--- a/Openshift-EE/pipelines/Prometheus/stages/3-functional/ELHN-deploy-prometheus/prometheus-provision
+++ b/Openshift-EE/pipelines/Prometheus/stages/3-functional/ELHN-deploy-prometheus/prometheus-provision
@@ -10,22 +10,26 @@ sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'cd e2e-opens
 }
 
 node() {
-job_id=$(echo $1)
-pipeline_id=$(echo $2)
-commit_id=$(echo $3)
-case_id=ELHN
+job_id=$(echo $1) #Gitlab job id obtain from the gitlab env ($CI_JOB_ID).
+pipeline_id=$(echo $2) # Gitlab pipeline id obtained from gitlab env ($CI_PIPELINE_ID).
+commit_id=$(echo $3) #Gitlab commit id Obtained fron gilab env ($CI_COMMIT_SHA).
+case_id=ELHN #test case ID.
 
 time="date"
 current_time=$(eval $time)
 
+#Creating e2e custom resource result for the test.
+
 bash Openshift-EE/utils/e2e-cr jobname:prometheus-provision jobphase:Waiting
 bash Openshift-EE/utils/e2e-cr jobname:prometheus-provision jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" 
  
-# Removing test_id from e2e-result.yml spec for simple mode
-#sed -i "s/-<job_id>/ /g" Openshift-EE/utils/result-volume-replica-distribution.yml
+################
+# LitmusBook 1 #
+################
 
-echo "*******Deploying Prometheus Application****"
-#kubectl apply -f Openshift-EE/utils/result-prometheus-provision.yml
+''' Deploying Prometheus Application '''
+
+#testcase for prometheus deployment is derived from  litmus job test_vars.yml
 
 test_name=$(bash Openshift-EE/utils/generate_test_name testcase=prometheus-deployment metadata="")
 echo $test_name
@@ -37,23 +41,29 @@ run_test=apps/prometheus/deployers/run_litmus_test.yml
 
 cat $run_test
 
-
+# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
 bash ../Openshift-EE/utils/litmus_job_runner label='app:prometheus-deployment-litmus' job=$run_test
 
 echo "Dumping state of cluster post job run"; echo ""
 cd ..
+# Get the cluster state Once the litmus jobs completed.
 bash Openshift-EE/utils/dump_cluster_state;
+# Update the e2e event for the job.
 bash Openshift-EE/utils/event_updater jobname:prometheus-provision $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
 
-
+# Update result of the test case in github mayadata-io/e2e-openshift repository.
 if [ "$?" != "0" ]; then
 #python3 Openshift-EE/utils/result/result_update.py $job_id ELHN 3-functional "Deploying prometheus application" Fail $pipeline_id "$current_time" $commit_id $gittoken
 exit 1;
 fi
 
+################
+# LitmusBook 2 #
+################
 
-echo "*******Deploying Prometheus Loadgen Application****"
-#kubectl apply -f Openshift-EE/utils/result-loadgen-provision.yml
+''' Deploying Prometheus Loadgen Application '''
+
+#testcase for prometheus loadgen is derived from  litmus job test_vars.yml
 
 test_name=$(bash Openshift-EE/utils/generate_test_name testcase=avalanche-deployment metadata="")
 echo $test_name
@@ -65,20 +75,62 @@ run_test=apps/prometheus/loadgen/run_litmus_test.yml
 
 cat $run_test
 
+# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
 bash ../Openshift-EE/utils/litmus_job_runner label='app:prometheus-loadgen-litmus' job=$run_test 
+
 
 echo "Dumping state of cluster post job run"; echo ""
 cd ..
+#Get the cluster state Once the litmus jobs completed.
 bash Openshift-EE/utils/dump_cluster_state;
+#Update the e2e event for the job
 bash Openshift-EE/utils/event_updater jobname:prometheus-provision $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
 
+# Update the result of the test case in github mayadata-io/e2e-openshift repository.
 if [ "$?" != "0" ]; then
 #python3 Openshift-EE/utils/result/result_update.py $job_id ELHN 3-functional "Deploying prometheus loadgen application" Fail $pipeline_id "$current_time" $commit_id $gittoken
 exit 1;
 fi
 
+################
+# LitmusBook 3 #
+################
+
+''' Deploying Prometheus Liveness Job '''
+
+# testcase for prometheus liveness is derived from litmus job vars.yml
+
+test_name=$(bash Openshift-EE/utils/generate_test_name testcase=prometheus-liveness metadata="")
+echo $test_name
+
+cd litmus
+
+echo "Running the litmus test.."
+run_test=apps/prometheus/liveness/run_litmus_test.yml
+
+cat $run_test
+
+# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
+bash ../Openshift-EE/utils/litmus_job_runner label='app:litmus-prometheus-liveness' job=$run_test 
+
+
+echo "Dumping state of cluster post job run"; echo ""
+cd ..
+#Get the cluster state Once the litmus jobs completed.
+bash Openshift-EE/utils/dump_cluster_state;
+#Update the e2e event for the job
+bash Openshift-EE/utils/event_updater jobname:prometheus-provision $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
+
+# Update the result of the test case in github mayadata-io/e2e-openshift repository.
+if [ "$?" != "0" ]; then
+#python3 Openshift-EE/utils/result/result_update.py $job_id ELHN 3-functional "Deploying prometheus liveness job" Fail $pipeline_id "$current_time" $commit_id $gittoken
+exit 1;
+fi
+
+# Update the e2e cr once the job is completed
+testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
 current_time=$(eval $time)
-bash Openshift-EE/utils/e2e-cr jobname:prometheus-provision jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
+bash Openshift-EE/utils/e2e-cr jobname:prometheus-provision jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:"$testResult"
 #python3 Openshift-EE/utils/result/result_update.py $job_id ELHN 3-functional "Scale the statefulset application replicas and verify the ring configuration" Pass $pipeline_id "$current_time" $commit_id $gittoken
 
 }
