Refactor[script]: Updated the test scripts for jiva pipeline (#418)
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>

diff --git a/Openshift-EE/utils/e2e_job_runner b/Openshift-EE/utils/e2e_job_runner
--- a/Openshift-EE/utils/e2e_job_runner
+++ b/Openshift-EE/utils/e2e_job_runner
@@ -4,15 +4,15 @@ job_retry_count=0
 pod_retry_count=0
 container_retry_count=0
 job_state_retry_count=0
-litmus_job_label_key=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 1)
-litmus_job_label_value=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 2)
-litmus_job_file=$(echo $2 | cut -d "=" -f 2)
+e2e_job_label_key=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 1)
+e2e_job_label_value=$(echo $1 | cut -d "=" -f 2 | cut -d ":" -f 2)
+e2e_job_file=$(echo $2 | cut -d "=" -f 2)
 
-echo "Running the litmus test.."
+echo "Running the e2e test.."
 
-jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.metadata.labels.${litmus_job_label_key}==\"${litmus_job_label_value}\")].metadata.name}'"
+jobNameCmd="kubectl get jobs -n e2e --no-headers -o jsonpath='{.items[?(@.metadata.labels.${e2e_job_label_key}==\"${e2e_job_label_value}\")].metadata.name}'"
 
-job_deploy_out=$(kubectl create -f ${litmus_job_file}) && \
+job_deploy_out=$(kubectl create -f ${e2e_job_file}) && \
 job_name=$(eval ${jobNameCmd}); retcode=$?
 
 while [ -z "$job_name" ]; do
@@ -24,31 +24,31 @@ while [ -z "$job_name" ]; do
   job_name=$(eval ${jobNameCmd});
 done
 chmod 755 ../Openshift-EE/utils/error_handler
-bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to run litmusbook, exiting" action="exit"
+bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to run e2ebook, exiting" action="exit"
     
-## Obtain the litmus pod name 
+## Obtain the e2e pod name 
 
-litmusPodCmd="kubectl get pod --no-headers -n litmus -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
-litmus_pod=$(eval ${litmusPodCmd}); retcode=$?
-while [ -z "$litmus_pod" ]; do
+e2ePodCmd="kubectl get pod --no-headers -n e2e -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
+e2e_pod=$(eval ${e2ePodCmd}); retcode=$?
+while [ -z "$e2e_pod" ]; do
   sleep 15
   pod_retry_count=$((pod_retry_count+1))
     if [[ "$pod_retry_count" -eq "15" ]]; then
       echo "unable to get POD_NAME"; exit 1;
     fi
-  pod_name=$(eval ${litmusPodCmd});
+  pod_name=$(eval ${e2ePodCmd});
 done
 
-bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to find litmus test runner pod, exiting" action="exit"
+bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to find e2e test runner pod, exiting" action="exit"
 
 ## Wait till the ansibletest container terminates && also confirm job completion status. This is done to ensure
 ## that execution of auxiliary containers such as loggers is completed. Getting the ansibletest ccontainer to completed state 
 ## satisfies the "necessary" condition for test job completion
 
-containerStateCmd="kubectl get pod ${litmus_pod} -n litmus -o jsonpath='{.status.containerStatuses[?(@.name==\"ansibletest\")].state}'"
-jobStateCmd="kubectl get pod ${litmus_pod} --no-headers -n litmus -o custom-columns=:status.phase"
+containerStateCmd="kubectl get pod ${e2e_pod} -n e2e -o jsonpath='{.status.containerStatuses[?(@.name==\"ansibletest\")].state}'"
+jobStateCmd="kubectl get pod ${e2e_pod} --no-headers -n e2e -o custom-columns=:status.phase"
 
-## TODO: Consider cases where litmus pod is evicted
+## TODO: Consider cases where e2e pod is evicted
 
 while true; do
   cstate=$(eval ${containerStateCmd}); rc=$?
@@ -64,7 +64,7 @@ while true; do
       else break;
       fi
     else
-      echo "unable to get litmus container status"; exit 1
+      echo "unable to get e2e container status"; exit 1
     fi
   fi
 done
@@ -80,11 +80,11 @@ while true; do
     sleep 10
     job_state_retry_count=$((job_state_retry_count+1))
     if [[ "$job_state_retry_count" -eq "10" ]]; then
-      echo "unable to get litmus job status"; exit 1;
+      echo "unable to get e2e job status"; exit 1;
     fi  
   fi
 done
-echo "Litmus test run Job has completed"
+echo "e2e test run Job has completed"
 
-echo "Dumping Litmus test pod logs for debug"; echo ""
-kubectl logs $litmus_pod -n litmus -c ansibletest
+echo "Dumping e2e test pod logs for debug"; echo ""
+kubectl logs $e2e_pod -n e2e -c ansibletest
