retry count is added to the script
Signed-off-by: sushma hegde <sushma.hegde@mayadata.io>

diff --git a/Openshift-EE/utils/litmus_job_runner b/Openshift-EE/utils/litmus_job_runner
--- a/Openshift-EE/utils/litmus_job_runner
+++ b/Openshift-EE/utils/litmus_job_runner
@@ -23,13 +23,30 @@ bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to run litmusboo
 
 litmusPodCmd="kubectl get pod --no-headers -n litmus -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
 
-while true; do 
+# Loop till running litmus pod is got. If not able to find the pod, print error message
+# number of times we want to try again to get the name of litmus pod
+let retry_count=7  
+
+while true; do
   litmus_pod=$(eval ${litmusPodCmd}); rc=$?
-  if [[ $rc -eq 0 && -z ${litmus_pod} ]]; then  # if pod is not found it returns null. If pod name is not got sleep for 5 sec and try again.
-    sleep 5                           
-  else break;   # if you get the pod name exit from while loop
+  if [[ $rc -eq 0 ]]; then
+    # if pod is not found it returns null. If pod name is not got sleep for 5 sec sec and try again.
+    if [[ -z ${litmus_pod} ]]; then   
+      sleep 5
+      retry_count=$((retry_count-1))
+      echo "unable to get litmus pod name....trying again"
+      if [[ $retry_count -eq 0 ]]; then
+        # retry count is over.. pod is not found.. exit from while loop by printing error message.
+        echo "unable to get litmus pod name exiting"  
+        exit 1;
+      fi
+    # if pod is found,exit from while loop
+    else      
+      break;
+    fi
   fi
 done
+
 
 ## Wait till the ansibletest container terminates && also confirm job completion status. This is done to ensure
 ## that execution of auxiliary containers such as loggers is completed. Getting the ansibletest ccontainer to completed state 
