Included app kill script in pipeline
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>

diff --git a/Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/1PP5-app-kill/app-kill b/Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/1PP5-app-kill/app-kill
--- a/Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/1PP5-app-kill/app-kill
+++ b/Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/1PP5-app-kill/app-kill
@@ -1,7 +1,6 @@
 #!/bin/bash
 set -x
 
-
 pod() {
 echo $CI_JOB_ID
 ###clone e2e-openshift-repo
@@ -12,48 +11,86 @@ sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'cd e2e-opens
 
 node() {
 job_id=$(echo $1)
-echo $job_id
-echo "*********Applying e2e-crd***********"
-kubectl apply -f Openshift-EE/utils/e2e-crd.yml
-
-echo "****Creating e2e-crd********"
-cat Openshift-EE/utils/e2e-result.yml > app-kill-result.yml
-sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/app-kill/g" -e"s/<job_id>/$job_id/g" app-kill-result.yml
 
 time="date"
 current_time=$(eval $time)
-sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" app-kill-result.yml
-kubectl apply -f app-kill-result.yml
-cat app-kill-result.yml
 
-echo "*******Deploying Application****"
-sleep 5
-echo "      Application-Deployment: Pass" >> app-kill-result.yml
-cat app-kill-result.yml
-kubectl apply -f app-kill-result.yml
+present_dir=$(pwd)
+echo $present_dir
 
-echo "*******Generating load**********"
-sleep 5
-echo "      Application-Loadgen: Pass" >> app-kill-result.yml
-cat app-kill-result.yml
-kubectl apply -f app-kill-result.yml
+bash Openshift-EE/utils/e2e-cr jobname:app-kill jobphase:Waiting
+bash Openshift-EE/utils/e2e-cr jobname:app-kill jobphase:Running init_time:"$current_time"
 
-echo "*******Killing Application************"
-sleep 5
-echo "      App-Kill: Fail" >> app-kill-result.yml
-cat app-kill-result.yml
-kubectl apply -f app-kill-result.yml
+echo "*******Deploying Busybox-sts Application****"
 
-echo "*******Deprovisioning Application******"
-sleep 5
-echo "      Application-Deprovisioning: Pass" >> app-kill-result.yml
-cat app-kill-result.yml
-kubectl apply -f app-kill-result.yml
+test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-app-kill metadata="")
+echo $test_name
+cd litmus
+echo "Running the litmus test for Busybox Deployment.."
+
+cp apps/busybox/deployers/run_litmus_test.yml busybox_app_kill.yml
+sed -i -e 's/app: busybox-litmus/app: deploy-busybox-app-kill/g' \
+-e 's/value: 'app=busybox-sts'/value: 'app=busybox-kill'/g' \
+-e 's/value: statefulset/value: deployment/g' \
+-e 's/value: app-busybox-ns/value: app-kill/g' busybox_app_kill.yml
+
+cat busybox_app_kill.yml
+
+bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-app-kill' job=busybox_app_kill.yml
+cd ..
+bash Openshift-EE/utils/dump_cluster_state;
+bash Openshift-EE/utils/event_updater jobname:app-kill $test_name
+if [ "$?" != "0" ]; then
+exit 1;
+fi
+
+echo "*******Performing Application pod Failure Chaos**********"
+
+test_name=$(bash Openshift-EE/utils/generate_test_name testcase=app-kill metadata="")
+echo $test_name
+cd litmus
+
+sed -i -e 's/app=jenkins-app/app=busybox-kill/g' \	
+-e 's/value: app-jenkins-ns/value: app-kill/g' apps/jenkins/chaos/app_pod_failure/run_litmus_test.yml
+
+echo "Running the litmus test for Busybox Deployment Scaleup.."
+run_test=apps/jenkins/chaos/app_pod_failure/run_litmus_test.yml
+cat $run_test
+
+bash ../Openshift-EE/utils/litmus_job_runner label='name:application-pod-failure' job=$run_test
+cd ..
+bash Openshift-EE/utils/dump_cluster_state;
+bash Openshift-EE/utils/event_updater jobname:app-kill $test_name
+
+if [ "$?" != "0" ]; then
+exit 1;
+fi
+
+echo "********Deprovisioning Busybox Application*******"
+
+test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-app-kill metadata="")
+echo $test_name
+cd litmus
+
+cp apps/busybox/deployers/run_litmus_test.yml deprovision_app_kill.yml
+sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deployment-deprovision/g' \
+-e 's/app: busybox-litmus/app: busybox-deprovision-app-kill/g' \
+-e 's/value: 'app=busybox-sts'/value: 'app=busybox-app-kill'/g' \
+-e 's/value: statefulset/value: deployment/g' \
+-e 's/value: app-busybox-ns/value: app-kill/g'
+-e 's/value: provision/value: deprovision/g' deprovision_app_kill.yml
+
+echo "Running the litmus test for Busybox Deployment Scaleup.."
+#run_test=apps/busybox/deployers/run_litmus_test.yml
+cat deprovision_mem_check.yml
+
+bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-app-kill' job=deprovision_app_kill.yml
+cd ..
+bash Openshift-EE/utils/dump_cluster_state;
+bash Openshift-EE/utils/event_updater jobname:app-kill $test_name
 
 current_time=$(eval $time)
-sed -i -e "s/<test-finish>/$current_time/g" app-kill-result.yml
-sed -i -e "s/<test-result>/Fail/g" app-kill-result.yml
-cat app-kill-result.yml
+bash Openshift-EE/utils/e2e-cr jobname:app-kill jobphase:Completed end_time:"$current_time" test_result:Pass
 }
 
 if [ "$1" == "node" ];then
